project:
  type: website

website:
  title: "iBridges Training"
  page-navigation: true
  page-footer:
    right: "This website is built and maintained with ☕ and [Quarto](https://quarto.org/)."
  sidebar:
    tools:
      - icon: github
        menu:
          - text: Source code
            url:  https://github.com/iBridges-for-iRODS/iBridges-Training
          - text: Report an issue
            url:  https://github.com/iBridges-for-iRODS/iBridges-Training/issues
    search: true
    pinned: true
    alignment: center
    style: docked
    collapse-level: 2
    logo: img/logo.png
    logo-alt: "Logo of iBridges"
    contents:
      - section: "Course information"
        contents:
          - href: index.qmd
            text: Welcome
          - href: prerequisites.qmd
            text: Prerequisites
      - section: "iBridges Beginner Training"
        contents:
          - href: introduction.qmd
            text: Introduction to iRODS and iBridges
          - href: ibridges-gui.qmd
            text: iBridges GUI
      - section: "iBridges for programmers"
        contents:
          - href: ibridges-api.qmd
            text: The iBridges API
          - href: compute-workflow.qmd
            text: iBridges and compute workflows

author:
  - name: Christine Staiger
    orcid: 0000-0002-6754-7647
  - name: Raoul Schram
    orcid: 0000-0001-6616-230X

format:
  html:
    theme: 
      light: [cosmo, styles/theme-light.scss]
    css:
      - css_files/hyperlinks.css
execute:
  python: system

